# Generated by Django 4.2.5 on 2024-12-30 18:50

import additem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(default=0, upload_to=additem.models.upload_to),
            preserve_default=False,
        ),
    ]
